FROM rocker/verse:latest

#RUN apt-get update -y
#RUN apt-get upgrade -y
#RUN apt-get install -y libudunits2-dev

#RUN Rscript -e "update.packages(ask=FALSE)"
RUN Rscript -e "install.packages('cgdsr', quiet = TRUE)"
